[workspace]
members = [
]
[package]
name = "ggml"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2021"
autobins = false

[lib]
name = "ggml"
path = "lib.rs"
crate-type = ["staticlib", "rlib"]
[dependencies]
lazy_static = "1.4.0"
libc= "0.2"
